version: "3.3"

services:
  nuxt-app:
    build: .
    container_name: polar.financial
    restart: always
    ports:
      - "7000:7000"
    command: "IS_TESTNET=true npm run start "
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge
